---
# Import interfaces from Netbox configured with the tag selected at line 13
# The output file will use AVD network_ports data model with a custom key.
# See the ReadMe.md file for example how to merge with existing network_ports data.  

- name: Get interfaces from netbox
  hosts: localhost
  gather_facts: false
  vars_files: ../vault.yml
  vars:
    netbox_url: "https://oohv9917.cloud.netboxapp.com"    # Replace with Netbox URL
    netbox_token: "{{vault_netbox_token}}"                # Replace with Netbox password
    target_tag: avd_import    #   Replace with tag you want to use.  Use the slug, not tag name.  Example tag AVD_IMPORT slug is avd_import(same as name but all lower case and spaces replaced with -)
    template_file: "../netbox/templates/network_ports.j2" # Template file in context to the playbook
    file_output: "../inventory/DataCenter/group_vars/CONNECTED_ENDPOINTS/netbox_import.yml" # Dedicated group_vars file for output

  tasks:
    - name: Get interfaces with AVD_IMPORT tag
      ansible.builtin.set_fact:
        netbox_interfaces: "{{ query('netbox.netbox.nb_lookup', 'interfaces', api_endpoint=netbox_url, token=netbox_token, api_filter='tag=' ~ target_tag)}}"

    - name: Generage AVD networks_ports structured data
      ansible.builtin.template:
        src: "{{template_file}}"
        dest: "{{file_output}}"
        mode: 0664

    # # Debbuging
    # # Uncomment to print interfaces to terminal
    # - name: debug
    #   debug:
    #     msg: "{{netbox_interfaces}}"
