---
# This playbook allows you to encrypt or decrypt bgp passwords using AVD encrypt and decrypt plugins
# Requires to have ansible galaxy collection `arista.avd` installed
# fill the `INPUTS` section 
# you can use tags to run only encrypt or decrpyt:
#   to encrypt: ansible-playbook bgp_passwords.yml --tags encrypt
#   to decrypt: ansible-playbook bgp_passwords.yml --tags decrypt

- name: BGP encrypt/decrypt
  hosts: localhost
  connection: local
  gather_facts: false
  ### INPUTS ###
  vars:
    plaintext_password: "arista123"         # plaintext password
    hashed_password: "WaB7A5IPqZBCtKRt0yV0GA=="   #hashed password
    key: "1.2.3.4"     # Neighbor IP or the BGP Peer Group Name in EOS.
  ###############

  tasks:
    - name: create hash from plaintext password
      tags: [ encrypt ]
      debug:
        msg: |
          The hashed password for BGP peer {{ key }} is:
          {{ plaintext_password |  arista.avd.encrypt(passwd_type='bgp', key=key) }}

    - name: decrypt password from hash
      tags: [ decrypt ]
      debug:
        msg: |
          Decrypted password for BGP peer {{ key }} is:
          {{ hashed_password | arista.avd.decrypt(passwd_type='bgp', key=key) }}