---
# This playbook allows you to encrypt or decrypt bgp passwords using AVD encrypt and decrypt plugins
# Requires to have ansible galaxy collection `arista.avd` installed

- name: BGP encrypt/decrypt
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - pause:
        prompt: |-
          What do you want to do ?
          1- encrypt
          2- decrypt
          enter 1 or 2
      register: main_input

    - set_fact:
        main_var: "{{ main_input.user_input }}"

    - pause:
        prompt: "Enter the plaintext password to encrypt"
      register: plaintext_password
      when: main_var == "1"

    - pause:
        prompt: "Enter the BGP peer IP or peer group name:"
      register: key
      when: main_var == "1"

    - name: Print encrypted BGP password
      debug:
        msg: |-
          The hashed password for BGP peer {{ key.user_input }} is:
          {{ plaintext_password.user_input |  arista.avd.encrypt(passwd_type='bgp', key=key.user_input) }}
      when: main_var == "1"

    - pause:
        prompt: "Enter the hashed password to decrypt"
      register: hashed_password
      when: main_var == "2"
    
    - pause:
        prompt: "Enter the BGP peer IP or peer group name:"
      register: key
      when: main_var == "2"

    - name: Print decrypted BGP password
      debug:
        msg: |-
          The hashed password for BGP peer {{ key.user_input }} is:
          {{ hashed_password.user_input |  arista.avd.decrypt(passwd_type='bgp', key=key.user_input) }}
      when: main_var == "2"